version: '3'
services:
  redis:
    image: redis
    restart: always
    hostname: redis
    container_name: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    # 目录映射
    volumes:
    
      - "/opt/docker/redis/data:/data" 
      - "/opt/docker/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf" 
      # - "/opt/docker/volume/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf" 
